### ISSUE TITLE
RuntimeError: Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label

### ISSUE THREAD

**Issue by jdejoode** [Dunedan/django-lockdown#10]
Is it possible to  use lockdown without also using the admin? 

My site does not need the admin, so all User, Auth stuff is disabled. 

I am running into this error because of that when trying to use lockdown:

     RuntimeError: Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label

**Comment by jdejoode** [comment]
This is caused by https://github.com/Dunedan/django-lockdown/blob/master/lockdown/forms.py#L3

Essentially I think a setting is needed to avoid automatically loading the admin and auth stuff. For instance: 

     LOCKDOWN_ADMIN = False

**Comment by Dunedan** [comment]
You can reproduce a similar error message, by running the following commands in a python shell:
```
>>> import django
>>> from django.conf import settings
>>> settings.configure()
>>> django.setup()
>>> from django.contrib.auth.forms import AuthenticationForm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/forms.py", line 12, in <module>
    from django.contrib.auth.models import User
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/usr/lib/python2.7/dist-packages/django/contrib/contenttypes/models.py", line 138, in <module>
    class ContentType(models.Model):
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 113, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

The import of `AuthenticationForm` is from https://github.com/Dunedan/django-lockdown/blob/master/lockdown/forms.py#L4

Looks like it's the same issue as mentioned in https://stackoverflow.com/questions/34754907/django-1-9-and-django-contrib-auth

I'll need to have a closer look into that issue and see if we can do something about it.

**Comment by jdejoode** [comment]
Well, I am just guessing, but a) I could simply copy past LockdownForm from lockdown.forms to a custom location and use that, or b) we could only import them if there is a setting that confirms users want to use that functionality. KISS

**Comment by Dunedan** [comment]
After looking into it a bit I realized that Djangos admin interfaces is not an issue at all here. `django-lockdown` should work fine without the django admin interface installed.

If I'm not mistaken your error message comes from not having `django.contrib.auth` in `INSTALLED_APPS`, which is independent of the django admin interface and belongs to Djangos authentication infrastructure. Therefore my suggestion would be to simply ensure that you have `django.contrib.auth` and `django.contrib.contenttypes` in your `INSTALLED_APPS`, which is usually the case for every new Django project created via `django-admin startproject`. If you don't add the middlewares responsible for authentication (`SessionMiddleware` and `AuthenticationMiddleware`) the performance impact of these additional `INSTALLED_APPS` should be negligble.

Your option a) would be an alternative solution as well. In that case you could use the `LOCKDOWN_FORM` setting to point `django-lockdown` to your copied `LockdownForm`.

Does that solve your problem?

**Comment by jdejoode** [comment]
Yes that does the trick. I would personally have preferred a solution without enabling django.contrib.auth as it is unnecessary overhead, but hey this works. 

Thanks for looking into it.

**Comment by Diptayan1995** [comment]
'I could simply copy past LockdownForm from lockdown.forms to a custom location and use that' ...
I do not understand what to copy and where to paste it ... can anybody please clarify?

**Comment by Dunedan** [comment]
@Diptayan1995 Can you please explain what you're trying to achieve? To me it sounds like you have a different issue. If that's the case, please open a new issue.

**Comment by Diptayan1995** [comment]
What I was trying to achieve is creating a rest api in django using my own custom model. So I eliminated the admin and auth stuffs from Installed apss, Middlewares and templates . Since then I was having this particular error while running it. This one - 'Model class django.contrib.auth.models.Permission doesn't declare an explicit app_label' . But then i changed the settings file and added this -
      
     REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'UNAUTHENTICATED_USER': None
}

It's working fine after that . I'm using django 2.0.6 .

Thank you.

**Comment by caw-ishikajain** [comment]
Not working for me tried below. Any suggestions?
```
 REST_FRAMEWORK = {
'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
'UNAUTHENTICATED_USER': None
}
```
Django==3.2.2
djangorestframework==3.12.4

**Comment by albjoaov** [comment]
Same error here. My libs:

Python 3.11.0
```
asgiref==3.5.2
Django==4.1.3
djangorestframework==3.14.0
psycopg2-binary==2.9.5
pytz==2022.6
sqlparse==0.4.3
```

**Comment by Dunedan** [comment]
Please don't comment on closed issues. If you have a new problem, please open a new issue as well.
