### ISSUE TITLE
io Import Error

### ISSUE THREAD

**Issue by tyclarke** [Dunedan/django-lockdown#18]
_from StringIO import StringIO_

**returns the error:**
_ModuleNotFoundError: No module named 'StringIO'_

**Change to:**

from io import StringIO

**Comment by Dunedan** [comment]
Where did you get this error from? This error shouldn't be from `django-lockdown` as it doesn't use `StringIO`.

**Comment by Dunedan** [comment]
Closing this now, as it doesn't seem to be related to this project.
