### ISSUE TITLE
Feature request - Allow Admins To Lockdown Site If Hacked

### ISSUE THREAD

**Issue by 9mido** [Dunedan/django-lockdown#19]
There should be a way to lockdown the site if currently being hacked. Maybe through the django admin dashboard where only admin staff/superuser users could login and make changes to it. Perhaps with a database 1 (on) or 0 (off) setting that updates the same row every time without adding new rows. Also make a setting to turn this feature and the database on or off. Do this without SSH into the server to stop gunicorn or the runserver command. This way, your site could still be running on the server and could help you further mitigate/understand what the hack is to better help you to try and stop it. 

This is similar to if someone steals your credit card and tries to buy something, lock them out and prevent them from going on a buying spree. 

```
LOCKDOWN_URL_EXCEPTIONS = (
    r'^/admin/.*$',
)
```
Or maybe it is best to just SSH and change LOCKDOWN_ENABLED to False in settings.py? Maybe there is a way to do it without a database table? Also wondering if it would be worth using a database or not for other settings to update/add to them?

**Comment by Dunedan** [comment]
Thanks for your request. After thinking a bit about it I wonder how useful that would be, as an attacker with write access to a website might just replace arbitrary parts of it. Therefore he'd be able to disable the lock down or replace the Django installation completely as well. What are your thoughts about that?

**Comment by 9mido** [comment]
You're welcome. Write access to the linux server itself do you mean? I see your point if that is the case. It all really depends on if the system admin takes security seriously in the first place. If they don't have good security defenses setup, and the hacker is somehow able to gain root access, they could very well cause some damage to the django installation and do whatever they want and disable the lockdown program as an example.  

One way to protect the admin login page is to use django-otp to enable two factor authentication where only true admin users can login. Even if a hacker has the admin's username and password, they still won't be able to login because they need the 2FA device. But if they have root access to the linux OS, they could still disable the django-otp 2FA for the admin dashboard if they edit settings.py. Then even a feature like this would be useless. 

However, if a system admin takes security seriously, then something like this will only add to their toolbelt. Things like Docker isolation and following something like [https://www.amazon.com/Mastering-Linux-Security-Hardening-intruders/dp/1838981772/ref=sr_1_1?dchild=1&qid=1597444083&refinements=p_27%3ADonald+A.+Tevault&s=books&sr=1-1&text=Donald+A.+Tevault](url) come to mind (highly recommended book by the way). 

Another use case for this type of feature is to lockdown your whole site if you are undergoing maintenance mode. If you don't want to take your entire site offline and tell all of your users you are undergoing upgrades. Even though something similar to that already exists. https://github.com/fabiocaccamo/django-maintenance-mode. But it does not have a LOCKDOWN_URL_EXCEPTIONS like your library does which could be more helpful in a hacker situation for an admin to take action from the admin dashboard to stop and understand the hack.

**Comment by Dunedan** [comment]
One of the core principles of `django-lockdown` has always been that the configuration for locked pages is done in a configuration file on disk. That has to stay available to keep backwards compatibility. What your feature request is essentially about is providing the ability to configure `django-lockdown` using the Django admin interface as well. However I currently don't see a way to have both, configuration file and admin interface, as I see no good way to keep settings made by either of them in sync with the other, as changes in the admin interface shouldn't modify with Django's configuration file. Do you have an idea how to solve that?

**Comment by Dunedan** [comment]
I'm closing this now, as there hasn't been further discussion in a while.
