### ISSUE TITLE
Future of django-lockdown

### ISSUE THREAD

**Issue by Dunedan** [Dunedan/django-lockdown#3]
According to PyPI `django-lockdown` is still quite popular (https://pypi.python.org/pypi/django-lockdown). Therefore it's a pity that there is no active development happening anymore. The latest changes date back one year and are done by @mkai on his fork (https://github.com/mkai/django-lockdown).

In #1 @carljm mentioned that he's searching for a new maintainer. I would be willing to step in (if desired) to keep `django-lockdown` up-to-date and to handle incoming pull requests, but I think there are some open questions which have to be discussed before.

I believe it would be benefical for `django-lockdown` to provide a single place for the code. I think the current two locations (Bitbucket and Github) as well as the two version control systems in use (`hg` and `git`) cause unnecessary overhead. I'd prefer seeing `django-lockdown` only on Github with dropped support for `hg`.

And what about the actual technical implementation? Would you grant permissions to push to the current project, would the official `django-lockdown` project move to the new maintainers account or would it even be placed in a completely new account? Same question about PyPI as well.

**Comment by carljm** [comment]
I would be happy to turn over control of the PyPI project to you as new maintainer. My preference would be to move the project to your GitHub account (or a GitHub account of your choice) and redirect from here to there, reducing confusion about the current maintainer. I have no problem with shutting down the Bitbucket repo, it's just a legacy thing (the project started on Bitbucket and hg) that I've never had time to deal with. If you move the canonical repo to a new github location, I would simply replace the Bitbucket repo with a link to the canonical location.

**Comment by Dunedan** [comment]
Ok, so let's do it. I granted push permissions to you on my fork of `django-lockdown` (https://github.com/Dunedan/django-lockdown), just in case this might become handy at some point.
I've also already integrated the patches made by @mkai in my forked repository and will continue with some cleanup throughout the next days, followed by a newly released version.
What's now missing is the control over the PyPI project and the redirection to my fork from here and from Bitbucket.

**Comment by carljm** [comment]
I mentioned in an issue over at your lockdown fork that in order to get things properly redirecting on GitHub, the best way is actually for me to "transfer" the repo over to your control. Otherwise your repo will continue to show that it was forked from mine, rather than being the canonical one. But I can't do that, because it clashes with your fork :-) So I think you should remove your fork, and then I'll transfer this repo over to you. Sorry :/

**Comment by Dunedan** [comment]
I has been deleted now, so you should be able to transfer the ownership, but I guess you'll have to create a fork on your own afterwards, to have some kind of redirecting at the old URL.

**Comment by carljm** [comment]
I've initiated the transfer, I think you have to accept it.

And I think GitHub offers an automatic redirect when a repo has been transferred. I may be wrong; we'll see.

**Comment by Dunedan** [comment]
Transfer finished and redirect seems to be working as well.

Regarding PyPI: I've the same username there as I've here.

**Comment by carljm** [comment]
I've added you as maintainer on PyPI, so you should be able to make releases. I've linked as best I can from the BitBucket repo; they don't seem to provide a redirect feature. Let me know if you need anything else!

**Comment by Dunedan** [comment]
Thanks, everything seems to be fine. I haven't tried to release a new version, but I properly see the project on PyPI. I'll close this issue now as the migration should be finished and will continue to work to get `django-lockdown` in shape for the most recent Django versions. :smiley:
